### ISSUE TITLE
Make a proper release

### ISSUE THREAD

**Issue by whiteandbased** [9mil-craftsman/UFH#5]
0.0.0.2 is confirmed working, so a proper release should be made with a changelog explaining what the mod actually is

**Comment by EpicallyWhite** [comment]
So what did you change?

**Comment by 9mil-craftsman** [comment]
But it has a changelog with every single change...

**Comment by whiteandbased** [comment]
needs a changelog in the release specifically, no one knows how to use github so theyre not going to go looking through the commits

**Comment by 9mil-craftsman** [comment]
No, you dont understand, the changelog is IN the .zip file with the rest of the mod

**Comment by whiteandbased** [comment]
yeah i know but theyre not going to see that when they click on the link to /releases
